let produtos=JSON.parse(localStorage.getItem("castroProdutos")||"[]");
function salvar(){localStorage.setItem("castroProdutos",JSON.stringify(produtos))}
function adicionarProduto(){produtos.push({nome:"",preco:"",img:"",link:"",descricao:"",b1:"",b2:"",b3:"",pros:"",contras:"",melhor:""});salvar();render()}
function atualizar(i,c,v){produtos[i][c]=v;salvar()}
function remover(i){produtos.splice(i,1);salvar();render()}
function render(){document.getElementById("lista").innerHTML=produtos.map((p,i)=>`<div class="product"><h3>Produto #${String(i+1).padStart(2,"0")}</h3><div class="grid">
<label>Nome<input value="${esc(p.nome)}" oninput="atualizar(${i},'nome',this.value)"></label><label>Preço<input value="${esc(p.preco)}" placeholder="R$ 99,90" oninput="atualizar(${i},'preco',this.value)"></label>
<label>URL da imagem<input value="${esc(p.img)}" placeholder="imagens/produto-01.jpg" oninput="atualizar(${i},'img',this.value)"></label><label>Link de afiliado<input value="${esc(p.link)}" placeholder="Cole seu link Shopee" oninput="atualizar(${i},'link',this.value)"></label>
<label>Descrição<textarea rows="3" oninput="atualizar(${i},'descricao',this.value)">${esc(p.descricao)}</textarea></label><label>Melhor para<input value="${esc(p.melhor)}" oninput="atualizar(${i},'melhor',this.value)"></label>
<label>Benefício 1<input value="${esc(p.b1)}" oninput="atualizar(${i},'b1',this.value)"></label><label>Benefício 2<input value="${esc(p.b2)}" oninput="atualizar(${i},'b2',this.value)"></label><label>Benefício 3<input value="${esc(p.b3)}" oninput="atualizar(${i},'b3',this.value)"></label>
<label>Prós<input value="${esc(p.pros)}" oninput="atualizar(${i},'pros',this.value)"></label><label>Contras<input value="${esc(p.contras)}" oninput="atualizar(${i},'contras',this.value)"></label></div><button class="remove" onclick="remover(${i})">Excluir</button></div>`).join("")}
function esc(s=""){return s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function gerar(){const t=document.getElementById("titulo").value,k=document.getElementById("keyword").value,d=document.getElementById("desc").value;let html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(d)}"><title>${esc(t)}</title><link rel="stylesheet" href="style.css"></head><body><main class="container"><h1>${esc(t)}</h1><p>${esc(k)} ajudam a deixar a rotina mais prática. Compare as opções abaixo antes de comprar.</p><p>Este artigo contém links de afiliado — ao comprar por eles você apoia o site sem pagar nada a mais.</p><h2>Melhores ${esc(k)}</h2>`;produtos.forEach((p,i)=>{let n=String(i+1).padStart(2,"0");html+=`<section class="product-card"><h2>Nº ${i+1} – ${esc(p.nome)}</h2><img src="${esc(p.img)}" alt="${esc(p.nome)} - ${esc(k)}" class="product-image"><p class="price">Preço: ${esc(p.preco)}</p><p><strong>Descrição:</strong> ${esc(p.descricao)}</p><p><strong>Principais benefícios:</strong></p><ul><li>${esc(p.b1)}</li><li>${esc(p.b2)}</li><li>${esc(p.b3)}</li></ul><p><strong>Prós:</strong> ${esc(p.pros)} &nbsp;|&nbsp; <strong>Contras:</strong> ${esc(p.contras)}</p><p><strong>Melhor para:</strong> ${esc(p.melhor)}</p><a href="${esc(p.link)}" target="_blank" rel="nofollow sponsored" class="buy-button">Ver melhor preço</a></section>`});html+=`<h2>Como escolher os melhores ${esc(k)}</h2><ol><li>Compare preço e frete.</li><li>Confira medidas e especificações.</li><li>Leia avaliações de compradores.</li><li>Priorize custo-benefício.</li></ol><h2>FAQ</h2><details><summary>Como escolher produtos para casa?</summary><p>Compare qualidade, preço, avaliações, medidas e necessidade de uso.</p></details><details><summary>Onde encontrar achadinhos para casa?</summary><p>Compare ofertas em marketplaces e confira o custo total antes da compra.</p></details><h2>Conclusão</h2><p>Compare os produtos e escolha a opção que melhor atende sua necessidade e orçamento.</p></main></body></html>`;document.getElementById("saida").value=html}
function baixar(){gerar();const b=new Blob([document.getElementById("saida").value],{type:"text/html;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="artigo-castro-decor.html";a.click();URL.revokeObjectURL(a.href)}
render();